<?php
require_once __DIR__ . '/../includes/bootstrap.php';
        include LEGACY_BASE_PATH . '/includes/auth_check.php';
        include LEGACY_BASE_PATH . '/includes/layout_start.php';
        include LEGACY_BASE_PATH . '/includes/functions.php';
        


?>

        <div id="printableArea" class="container-fluid dashboard-page-content mt-5 pt-3">
            <div class="print-header">
                <h3>Sales Report</h3>
                <!-- Date range and generation info will be updated by JS or remain placeholder for print. -->
                <p id="reportDateRange">Date Range: Loading...</p>
                <p>Generated by: <?php echo htmlspecialchars($_SESSION["username"] ?? 'N/A'); ?> on <?php echo date('Y-m-d H:i:s'); ?></p>
            </div>

            <!-- Alerts will now be handled by JavaScript. This PHP block is removed from here. -->

            <div class="card mb-4 no-print">
                <div class="card-header">
                    Filter Sales Report
                </div>
                <div class="card-body">
                    <!-- Form for filtering sales data. Submission handled by JavaScript. -->
                    <form id="filterForm" class="row g-3 align-items-end">
                        <div class="col-md-3">
                            <label for="start_date" class="form-label">Start Date:</label>
                            <input type="date" class="form-control" id="start_date" name="start_date" value="" required>
                        </div>
                        <div class="col-md-3">
                            <label for="end_date" class="form-label">End Date:</label>
                            <input type="date" class="form-control" id="end_date" name="end_date" value="" required>
                        </div>
                        <div class="col-md-3">
                            <label for="records_per_page" class="form-label">Records per page:</label>
                            <select class="form-select" id="records_per_page" name="records_per_page">
                                <!-- Options will be dynamically set or default to 10-100 -->
                                <option value="10">10</option>
                                <option value="20">20</option>
                                <option value="30">30</option>
                                <option value="40">40</option>
                                <option value="50">50</option>
                                <option value="60">60</option>
                                <option value="70">70</option>
                                <option value="80">80</option>
                                <option value="90">90</option>
                                <option value="100">100</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <button type="submit" class="btn btn-primary w-100">Apply Filter</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="mb-4 text-end no-print">
                <button class="btn btn-secondary" onclick="printReportInNewWindow()"><i class="fas fa-print"></i> Print Report</button>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    Summary for Selected Period
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <div class="summary-box bg-success text-white text-center p-3 rounded shadow-sm">
                                <h4>Total Sales Amount:</h4>
                                <h3 id="totalSalesAmount">Loading...</h3>
                            </div>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="summary-box bg-info text-white text-center p-3 rounded shadow-sm">
                                <h4>Total Items Sold:</h4>
                                <h3 id="totalItemsSold">Loading...</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    Detailed Sales Transactions
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="salesTable">
                            <thead>
                                <tr>
                                    <th>Sale ID</th>
                                    <th>Date</th>
                                    <th>Cashier</th>
                                    <th>Items Sold</th>
                                    <th>Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- Sales data will be loaded dynamically by public/js/detailed_sales_report_script.js -->
                                <tr>
                                    <td colspan="5" class="text-center">Loading sales data...</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <!-- Pagination controls will be built dynamically by JavaScript -->
                    <nav id="paginationNav" aria-label="Sales Pagination" class="mt-4 no-print">
                        <!-- Pagination links will be injected here by JavaScript -->
                    </nav>

                </div>
            </div>
        </div>
    </div>
</div>

<?php
        // Close layout (footer, scripts, closing tags)
        include LEGACY_BASE_PATH . '/includes/layout_end.php'; ?>
<!-- NEW: Include the specific JavaScript for detailed sales reports to handle AJAX operations -->
<script src="<?= LEGACY_BASE_URL ?>/public/js/detailed_sales_report_script.js?v=<?= filemtime(LEGACY_BASE_PATH . '/public/js/detailed_sales_report_script.js') ?>"></script>
</body>
</html>


