<?php
require_once __DIR__ . '/../includes/bootstrap.php';
// views/sales_analytics.php

// --- Includes and Initial Setup ---
include LEGACY_BASE_PATH . '/includes/auth_check.php';
include LEGACY_BASE_PATH . '/includes/layout_start.php';
include LEGACY_BASE_PATH . '/includes/functions.php';
include LEGACY_BASE_PATH . '/config/db.php'; 
include LEGACY_BASE_PATH . '/includes/sales_analytics_function.php'; 

// =========================================================================
// Connection Setup
// =========================================================================
global $pdo; 
/** @var PDO $conn */
$conn = $pdo; 

// --- Date Filtering Logic ---
$start_date = isset($_GET['start_date']) ? sanitize_input($_GET['start_date']) : date('Y-m-01');
$end_date = isset($_GET['end_date']) ? sanitize_input($_GET['end_date']) : date('Y-m-d');

$message = '';
$message_type = '';

// --- Data Arrays ---
$top_selling_products = [];
$sales_by_cashier = [];
$daily_sales_trend = [];

try {
    // Fetch data using the separated functions
    $top_selling_products = getTopSellingProducts($conn, $start_date, $end_date);
    $sales_by_cashier = getSalesByCashier($conn, $start_date, $end_date);
    $daily_sales_trend = getDailySalesTrend($conn, $start_date, $end_date);

} catch (PDOException $e) {
    $message .= "Database error fetching analytics data: " . $e->getMessage();
    $message_type = 'danger';
}

// Clean up the connection object
$conn = null;

// =========================================================================
// HTML / View Code (Body content remains unchanged)
// =========================================================================
?>

        <div id="printableArea" class="container-fluid dashboard-page-content mt-5 pt-3">
            <div class="print-header">
                <h3>Sales Analytics Report</h3>
                <p id="reportDateRange">Date Range: <?php echo htmlspecialchars($start_date); ?> to <?php echo htmlspecialchars($end_date); ?></p>
                <p>Generated by: <?php echo htmlspecialchars($_SESSION["username"] ?? 'N/A'); ?> on <?php echo date('Y-m-d H:i:s'); ?></p>
            </div>

            <?php if (!empty($message)): ?>
                <div class="alert alert-<?php echo $message_type; ?> alert-dismissible fade show no-print" role="alert">
                    <?php echo $message; ?>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <div class="card mb-4 no-print">
                <div class="card-header">
                    Filter Sales Analytics
                </div>
                <div class="card-body">
                    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="get" class="row g-3 align-items-end">
                        <div class="col-md-4">
                            <label for="start_date" class="form-label">Start Date:</label>
                            <input type="date" class="form-control" id="start_date" name="start_date" value="<?php echo htmlspecialchars($start_date); ?>" required>
                        </div>
                        <div class="col-md-4">
                            <label for="end_date" class="form-label">End Date:</label>
                            <input type="date" class="form-control" id="end_date" name="end_date" value="<?php echo htmlspecialchars($end_date); ?>" required>
                        </div>
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-primary w-100">Apply Filter</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="mb-4 text-end no-print">
                <button class="btn btn-secondary" onclick="printReportInNewWindow()"><i class="fas fa-print"></i> Print Report</button>
            </div>

            <div class="card">
                <div class="card-header">
                    Sales Analytics Data
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped">
                                    
                                    <thead>
                                        <tr>
                                            <th colspan="3" class="table-primary text-center">Top 10 Selling Products (by Quantity)</th>
                                        </tr>
                                        <tr>
                                            <th>Product</th>
                                            <th>Quantity Sold</th>
                                            <th>Total Sales (Product)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (!empty($top_selling_products)): ?>
                                            <?php foreach ($top_selling_products as $product): ?>
                                                <tr>
                                                    <td><?php echo htmlspecialchars($product['product_name']); ?></td>
                                                    <td><?php echo number_format($product['total_quantity_sold']); ?></td>
                                                    <td>₱<?php echo number_format($product['total_product_sales'], 2); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td colspan="3" class="text-center">No top-selling products found for this period.</td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>

                                    <thead>
                                        <tr>
                                            <th colspan="3" class="table-success text-center">Daily Sales Trend</th>
                                        </tr>
                                        <tr>
                                            <th>Date</th>
                                            <th colspan="2">Total Sales</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (!empty($daily_sales_trend)): ?>
                                            <?php foreach ($daily_sales_trend as $daily_sale): ?>
                                                <tr>
                                                    <td><?php echo htmlspecialchars($daily_sale['sale_day']); ?></td>
                                                    <td colspan="2">₱<?php echo number_format($daily_sale['daily_total_sales'], 2); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td colspan="3" class="text-center">No daily sales trend data found for this period.</td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>

                                    <thead>
                                        <tr>
                                            <th colspan="3" class="table-info text-center">Sales by Cashier</th>
                                        </tr>
                                        <tr>
                                            <th>Cashier</th>
                                            <th>Total Sales</th>
                                            <th>Transactions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php if (!empty($sales_by_cashier)): ?>
                                            <?php foreach ($sales_by_cashier as $cashier): ?>
                                                <tr>
                                                    <td><?php echo htmlspecialchars($cashier['cashier_name']); ?></td>
                                                    <td>₱<?php echo number_format($cashier['total_sales_by_cashier'], 2); ?></td>
                                                    <td><?php echo number_format($cashier['total_transactions']); ?></td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td colspan="3" class="text-center">No cashier sales data found for this period.</td>
                                            </tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
        // Close layout (footer, scripts, closing tags)
        include LEGACY_BASE_PATH . '/includes/layout_end.php'; ?>
<script src="<?= LEGACY_BASE_URL ?>/public/js/sales_analytics.js"></script>
</body>
</html>


