<?php
require_once __DIR__ . '/../includes/bootstrap.php';
// views/stock_report.php

// --- Includes and Initial Setup ---
include LEGACY_BASE_PATH . '/includes/auth_check.php';
include LEGACY_BASE_PATH . '/includes/layout_start.php';
include LEGACY_BASE_PATH . '/includes/functions.php';             // Contains general utility functions
include LEGACY_BASE_PATH . '/config/db.php';                      // **CRITICAL: Includes $pdo object**

// --- Date Filtering Logic ---
$start_date = isset($_GET['start_date']) ? sanitize_input($_GET['start_date']) : date('Y-m-01');
$end_date = isset($_GET['end_date']) ? sanitize_input($_GET['end_date']) : date('Y-m-d');

// --- Pagination Logic ---
$allowed_records_per_page = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100];
$default_records_per_page = 10; 

$records_per_page = isset($_GET['per_page']) && in_array((int)$_GET['per_page'], $allowed_records_per_page) ? (int)$_GET['per_page'] : $default_records_per_page;

$current_page = isset($_GET['page']) && is_numeric($_GET['page']) ? (int)$_GET['page'] : 1;
if ($current_page < 1) {
    $current_page = 1;
}
$offset = ($current_page - 1) * $records_per_page;

// --- Sorting Logic ---
$allowed_sort_orders = ['quantity_asc', 'quantity_desc', 'name_asc'];
$default_sort_order = 'quantity_asc';

$sort_order = isset($_GET['sort_order']) && in_array($_GET['sort_order'], $allowed_sort_orders) ? $_GET['sort_order'] : $default_sort_order;

$message = '';
$message_type = '';
$lowStockThreshold = 10;
$stockItems = [];

// =========================================================================
// FIX: Fetch data directly from the products table for an accurate report.
// =========================================================================
global $pdo; 
$conn = $pdo; // $conn is now the PDO connection object

try {
    // Determine the sorting column and direction
    $order_by = '';
    if ($sort_order === 'quantity_asc') {
        $order_by = 'p.stock_quantity ASC';
    } elseif ($sort_order === 'quantity_desc') {
        $order_by = 'p.stock_quantity DESC';
    } elseif ($sort_order === 'name_asc') {
        $order_by = 'p.name ASC';
    }

    // SQL query to count total products for pagination
    $countSql = "SELECT COUNT(*) FROM products";
    $countStmt = $conn->prepare($countSql);
    $countStmt->execute();
    $total_products = $countStmt->fetchColumn();

    // Calculate total pages
    $total_pages = ceil($total_products / $records_per_page);

    // Adjust current page and offset
    if ($total_products > 0 && $current_page > $total_pages) {
        $current_page = $total_pages;
        $offset = ($current_page - 1) * $records_per_page;
    } elseif ($total_products == 0 && $current_page > 1) {
        $current_page = 1;
        $offset = 0;
    }

    // SQL query to fetch product data with joins for category and supplier names
    $sql = "SELECT p.id as product_id, 
                   p.name as product_name, 
                   p.price as selling_price,
                   p.cost_price as cost_price,
                   p.stock_quantity as calculated_quantity,
                   c.name as category_name,
                   s.name as supplier_name
            FROM products p
            LEFT JOIN categories c ON p.category_id = c.id
            LEFT JOIN suppliers s ON p.supplier_id = s.id
            ORDER BY {$order_by}
            LIMIT :limit OFFSET :offset";

    $stmt = $conn->prepare($sql);
    $stmt->bindValue(':limit', $records_per_page, PDO::PARAM_INT);
    $stmt->bindValue(':offset', $offset, PDO::PARAM_INT);
    $stmt->execute();
    $stockItems = $stmt->fetchAll(PDO::FETCH_ASSOC);

} catch (Exception $e) {
    $message = "Error fetching stock data: " . $e->getMessage();
    $message_type = 'danger';
}

// Close database connection (PDO method)
$conn = null;


// --- View/Presentation (HTML starts here) ---
?>

        <div id="printableArea" class="container-fluid dashboard-page-content mt-5 pt-3">
            <div class="print-header">
                <h3>Stock Report (As of <?php echo htmlspecialchars($end_date); ?>)</h3>
                <p>Generated by: <?php echo htmlspecialchars($_SESSION["username"]); ?> on <?php echo date('Y-m-d H:i:s'); ?></p>
            </div>
            <?php if (!empty($message)): ?>
                <div class="alert alert-<?php echo $message_type; ?> alert-dismissible fade show no-print" role="alert">
                    <?php echo $message; ?>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php endif; ?>

            <div class="card mb-4 no-print">
                <div class="card-header">
                    Filter Stock Report
                </div>
                <div class="card-body">
                    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="get" class="row g-3 align-items-end">
                        <div class="col-md-3">
                            <label for="start_date" class="form-label">Start Date:</label>
                            <input type="date" class="form-control" id="start_date" name="start_date" value="<?php echo htmlspecialchars($start_date); ?>" required>
                        </div>
                        <div class="col-md-3">
                            <label for="end_date" class="form-label">End Date:</label>
                            <input type="date" class="form-control" id="end_date" name="end_date" value="<?php echo htmlspecialchars($end_date); ?>" required>
                        </div>
                        <div class="col-md-3">
                            <label for="per_page" class="form-label">Records per page:</label>
                            <select class="form-select" id="per_page" name="per_page">
                                <?php foreach ($allowed_records_per_page as $num): ?>
                                    <option value="<?php echo $num; ?>" <?php echo ($records_per_page == $num) ? 'selected' : ''; ?>>
                                        <?php echo $num; ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                         <div class="col-md-3">
                            <label for="sort_order" class="form-label">Sort by Quantity:</label>
                            <select class="form-select" id="sort_order" name="sort_order">
                                <option value="quantity_asc" <?php echo ($sort_order == 'quantity_asc') ? 'selected' : ''; ?>>Lowest First</option>
                                <option value="quantity_desc" <?php echo ($sort_order == 'quantity_desc') ? 'selected' : ''; ?>>Highest First</option>
                                <option value="name_asc" <?php echo ($sort_order == 'name_asc') ? 'selected' : ''; ?>>Product Name</option>
                            </select>
                        </div>
                        <div class="col-12 mt-3">
                            <button type="submit" class="btn btn-primary w-100">Apply Filter</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="mb-4 text-end no-print">
                <button class="btn btn-secondary" onclick="printReportInNewWindow()"><i class="fas fa-print"></i> Print Report</button>
            </div>

            <div class="card mb-4">
                <div class="card-header">
                    Stock Levels
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Product ID</th>
                                    <th>Product Name</th>
                                    <th>Category</th>
                                    <th>Supplier</th>
                                    <th>Stocks</th>
                                    <th>Cost Price</th>
                                    <th>Selling Price</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (!empty($stockItems)): ?>
                                    <?php foreach ($stockItems as $item): ?>
                                        <tr>
                                            <td><?php echo htmlspecialchars($item['product_id']); ?></td>
                                            <td><?php echo htmlspecialchars($item['product_name']); ?></td>
                                            <td><?php echo htmlspecialchars($item['category_name'] ?? 'N/A'); ?></td>
                                            <td><?php echo htmlspecialchars($item['supplier_name'] ?? 'N/A'); ?></td>
                                            <td><?php echo htmlspecialchars($item['calculated_quantity']); ?></td>
                                            <td>₱<?php echo number_format($item['cost_price'], 2); ?></td>
                                            <td>₱<?php echo number_format($item['selling_price'], 2); ?></td>
                                            <td>
                                                <?php
                                                    $statusClass = '';
                                                    $displayStatus = '';
                                                    
                                                    // Determine status based on quantity
                                                    if ($item['calculated_quantity'] <= 0) {
                                                        $statusClass = 'badge bg-danger';
                                                        $displayStatus = 'Out of Stock';
                                                    } elseif ($item['calculated_quantity'] <= $lowStockThreshold) {
                                                        $statusClass = 'badge bg-warning text-dark';
                                                        $displayStatus = 'Low Stock';
                                                    } else {
                                                        $statusClass = 'badge bg-success';
                                                        $displayStatus = 'In Stock';
                                                    }
                                                ?>
                                                <span class="<?php echo $statusClass; ?>">
                                                    <?php echo $displayStatus; ?>
                                                </span>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr>
                                        <td colspan="8" class="text-center">No product or stock data available for the selected period.</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>

                    <nav aria-label="Page navigation" class="no-print">
                        <ul class="pagination justify-content-center">
                            <?php 
                                // Simplified Pagination URL creation
                                $base_url_params = "&per_page={$records_per_page}&sort_order={$sort_order}&start_date={$start_date}&end_date={$end_date}";
                            ?>
                            <li class="page-item <?php echo ($current_page <= 1) ? 'disabled' : ''; ?>">
                                <a class="page-link" href="?page=<?php echo $current_page - 1 . $base_url_params; ?>" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                            <?php for ($i = 1; $i <= $total_pages; $i++): ?>
                                <li class="page-item <?php echo ($current_page == $i) ? 'active' : ''; ?>">
                                    <a class="page-link" href="?page=<?php echo $i . $base_url_params; ?>">
                                        <?php echo $i; ?>
                                    </a>
                                </li>
                            <?php endfor; ?>
                            <li class="page-item <?php echo ($current_page >= $total_pages) ? 'disabled' : ''; ?>">
                                <a class="page-link" href="?page=<?php echo $current_page + 1 . $base_url_params; ?>" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>

                </div>
            </div>
        </div>
    </div>
</div>

<?php
        // Close layout (footer, scripts, closing tags)
        include LEGACY_BASE_PATH . '/includes/layout_end.php'; ?>
        <script src="<?= LEGACY_BASE_URL ?>/public/js/stock_report.js?v=<?= filemtime(LEGACY_BASE_PATH . '/public/js/stock_report.js') ?>"></script>
</body>
</html>



